language: rust

branches:
  only:
    - master

cache: cargo

rust:
  - nightly
  - beta
  - 1.29.2
  - 1.30.1

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true

addons:
  apt:
    packages:
      - python3 # Needed for check_all.py

script: ./check_all.py
