[package]
name = "catty"
version = "0.1.0"
authors = ["Arnav Borborah <arnavborborah11@gmail.com>"]

[dependencies]

[dependencies.clap]
version = "2.32"
default-features = false
features = ["suggestions"]
